# Generated by Django 5.2.3 on 2026-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_alter_assignedtask_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
