# Generated by Django 5.2.3 on 2026-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_userprofile_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
